#!/bin/bash
#SBATCH --job-name=PlaAll
#SBATCH --partition=i72c512g,cpueicc,cpu6248R
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --output=logs/step_%A_%a.out
#SBATCH --error=logs/step_%A_%a.err
##SBATCH --exclusive


exe=/public/group/imp/zengch/LQCD/renorma/C_pt_load.py

mkdir -p logs

python "$exe"  > "logs/output.log" 2>&1
