"""Interactive manifest planning and correlator HDF5 preparation."""

from __future__ import annotations

from lamet_agent.core.llm import request_llm_text

from .agent import (
    PLAN_ACTION_SCHEMA,
    PLAN_TOOL_CATALOG,
    _PlanAgentSession,
    _apply_user_answer_to_candidate,
    _initial_planning_user_prompt,
    _mock_revision_patches,
    _parse_json_object,
    _planning_system_prompt,
    _run_planning_tool,
    run_interactive_plan,
)
from .conversion import (
    _choose_source_datasets,
    _copy_h5_attrs,
    _dataset_attrs,
    _dataset_names,
    _source_summary,
    _standard_dataset_paths,
    convert_correlator_h5,
    inspect_correlator_h5_files,
    plan_correlator_h5_conversions,
)
from .core import (
    CorrelatorH5Mapping,
    H5DatasetSummary,
    H5Inspection,
    IssueSeverity,
    PlanAgentState,
    PlanIssue,
    PlanProposal,
    PlanRunResult,
    _apply_one_json_patch,
    _artifacts_dir,
    _as_list,
    _dataclass_json,
    _expand_pt2_windows,
    _expand_tau_cuts,
    _get_path_value,
    _id_counts,
    _json_pointer_display,
    _json_pointer_parts,
    _make_full_variant,
    _make_quick_variant,
    _manifest_root,
    _merge_revision_edits,
    _normalise_pt2_windows,
    _planned_manifest_paths,
    _remove_edit_for_path,
    _resolve_manifest_path,
    _resolve_patch_parent,
    _set_kernel_scheme_from_renorm,
    _set_path_value,
    _shrink_list,
    _stage_parameter_gaps,
    _strict_manifest_issues,
    _strip_jsonc,
    _update_conversion_paths,
    apply_manifest_json_patches,
    build_repaired_manifests,
    check_manifest_draft,
    load_relaxed_manifest,
    validate_candidate_payload,
)
from .questions import (
    _ask_plan_agent_question,
    _coerce_user_answer_for_manifest_path,
    _get_dotted_path,
    _json_pointer_from_question_id,
    _manifest_question_id_from_user_input_action,
    _next_path_repair_question,
    _next_questions_for_state,
    _valid_plan_agent_question,
)
from .render import (
    _inconsistent_settings,
    _manifest_change_lines,
    _missing_parameters,
    _render_bullets,
    _render_proposal,
    _render_written_summary,
    _short_repr,
    write_planned_outputs,
)
