"""contract_baryon — Simplified baryon 3pt contraction without wicklib topology enumeration.

Topologies are enumerated directly from flavor content and permutation parity.
No need for wicklib's 3!×3! full expansion + adjacency matrix reconstruction.

Rules:
  1. A topology = bijection π: {src_slots}→{snk_slots} + current position
  2. π must conserve flavor: src_flavor[s] == snk_flavor[π(s)] for spectators,
     and src_flavor[cur_src]==cur_in, snk_flavor[cur_snk]==cur_out for current
  3. Sign = -(-1)^(parity(π))  (physical sign from fermion exchange)

Cases:
  - 3 flavors distinct → 1 bijection × 1 current = 1 topology
  - 2 identical + 1 distinct → 2 bijections × (1-2 cur) = 2-4 topologies
  - 3 identical → 6 bijections × 3 current = 18 topologies
"""

import itertools
from typing import Dict, List, Tuple

try:
    from .._wick_translate import _rename_op
except ImportError:
    import sys
    from pathlib import Path
    _pp = str(Path(__file__).resolve().parent.parent)
    if _pp not in sys.path:
        sys.path.insert(0, _pp)
    from _wick_translate import _rename_op

# ── Label conventions (same as original contract.py) ──
# No epsilon fixed indices — but slot→letter mapping is fixed.
SRC_EPS = {"a": "i", "b": "j", "c": "k"}
SNK_EPS = {"a": "l", "b": "m", "c": "n"}
SRC_SPIN = {"a": "A", "b": "B", "c": "D"}
SNK_SPIN = {"a": "G", "b": "H", "c": "I"}
SRC_COL = {"a": "i", "b": "j", "c": "k"}
SNK_COL = {"a": "l", "b": "m", "c": "n"}

_LIGHT = frozenset({"u", "d"})

_SLOTS = ("a", "b", "c")


def _var(f: str) -> str:
    return "prop_l" if f in _LIGHT else f"prop_{f}"


def _prop_label(src_slot: str, snk_slot: str) -> str:
    """Propagator label: src_spin·snk_spin·src_color·snk_color.

    Except sb (src=c, snk=c) reverses spin order.
    """
    if src_slot == "c" and snk_slot == "c":
        spin = f"{SNK_SPIN[snk_slot]}{SRC_SPIN[src_slot]}"  # ID
    else:
        spin = f"{SRC_SPIN[src_slot]}{SNK_SPIN[snk_slot]}"
    return f"wtzyx{spin}{SRC_COL[src_slot]}{SNK_COL[snk_slot]}"


def _output_label(src_slot: str, snk_slot: str) -> str:
    """Output label: snk_spin·src_spin·snk_color·src_color."""
    return f"{SNK_SPIN[snk_slot]}{SRC_SPIN[src_slot]}{SNK_COL[snk_slot]}{SRC_COL[src_slot]}"


# ── Topology enumeration ──

def _extract_flavors(op_input) -> Dict[str, str]:
    """Extract {slot: flavor} from baryon_operator() output."""
    op = op_input[0] if isinstance(op_input, tuple) else op_input
    tensors = op.tensors
    return {"a": tensors[1].flavor, "b": tensors[3].flavor, "c": tensors[4].flavor}


def _parity(perm: Dict[str, str]) -> int:
    """Parity of a permutation π: {a,b,c}→{a,b,c}."""
    # Count inversions
    items = list(perm.items())
    inversions = 0
    for i in range(len(items)):
        for j in range(i + 1, len(items)):
            s1, t1 = items[i]
            s2, t2 = items[j]
            # src order = s1,s2; dst order = t1,t2
            # inversion if dst order is opposite of src order
            if (s1 < s2 and t1 > t2) or (s1 > s2 and t1 < t2):
                inversions += 1
    return inversions % 2


# ── Main entry point ──

def contract_baryon_3pt_simple(
    sink, source, current,
) -> dict:
    """Baryon 3pt: enumerate topologies from flavors + permutations.

    Returns same dict structure as contract_baryon_3pt() for downstream codegen.

    Parameters
    ----------
    sink : tuple(Operator, SpinIndex)
    source : tuple(Operator, SpinIndex)
    current : generated by current_operator()

    Returns
    -------
    dict with keys:
        sink_terms : list of dict(einsum, sign, var_a, var_b, flavor_a, flavor_b, description)
        fwd_var, fwd_flavor, current_gamma
    """
    # Extract flavors
    src_flav = _extract_flavors(source)
    snk_flav = _extract_flavors(sink)

    # Extract current info
    cur_op = current[0] if isinstance(current, tuple) else current
    cur_tensors = cur_op.tensors
    cur_in = next(t.flavor for t in cur_tensors if t.type == "antiquark")
    cur_out = next(t.flavor for t in cur_tensors if t.type == "quark")
    cur_gamma = next(t.name for t in cur_tensors if t.type == "gamma")

    # ── Enumerate all bijections π: {a,b,c}→{a,b,c} ──
    terms = []
    seen = set()

    for perm_targets in itertools.permutations(_SLOTS):
        pi = dict(zip(_SLOTS, perm_targets))  # π[src] = dst

        # Check which connections can carry the current
        possible_currents = []
        for s in _SLOTS:
            t = pi[s]
            if src_flav[s] == cur_in and snk_flav[t] == cur_out:
                possible_currents.append((s, t))

        for cur_src, cur_snk in possible_currents:
            # Check spectator flavor conservation:
            # all non-current connections must conserve flavor
            spectator_ok = True
            for s in _SLOTS:
                if s == cur_src:
                    continue
                t = pi[s]
                if src_flav[s] != snk_flav[t]:
                    spectator_ok = False
                    break
            if not spectator_ok:
                continue

            # Build connection dict
            conn = {}
            for s in _SLOTS:
                t = pi[s]
                is_cur = (s == cur_src and t == cur_snk)
                conn[s] = (t, is_cur)

            # Deduplicate: same π+cur = same topology
            key = tuple(sorted(conn.items()))
            if key in seen:
                continue
            seen.add(key)

            # ── Gather spectator slots & determine prop/out labels ──
            spectator_slots = [s for s in _SLOTS if s != cur_src]

            # p1 = current propagator
            p1_label = _prop_label(cur_src, cur_snk)

            # Determine p2 and output from spectators, matching original codegen
            if "b" in spectator_slots and conn["b"][0] == "b":
                # b→b straight-through → p2 uses b, output uses other spectator
                p2_label = _prop_label("b", "b")
                other_s = [s for s in spectator_slots if s != "b"][0]
                output_label = _output_label(other_s, conn[other_s][0])
            elif spectator_slots:
                s0 = spectator_slots[0]
                p2_label = _prop_label(s0, conn[s0][0])
                other_s = [s for s in spectator_slots if s != s0][0]
                output_label = _output_label(other_s, conn[other_s][0])
            else:
                # Shouldn't happen for baryon 3pt
                p2_label = _prop_label("c", "c")
                output_label = _output_label("c", "c")

            # ── Build einsum string ──
            sb_case = (cur_src == "c" and cur_snk == "c")
            # In original code, the sb case swaps p1 to (a,a) and (b,b), not current
            if sb_case:
                # current on (c,c): use a→a, b→b as propagators
                einsum = (
                    "wtzyx, ijk, lmn, AB, GH, ID,"
                    f" {_prop_label('a','a')}, {_prop_label('b','b')}"
                    f" -> wtzyx{_output_label('c','c')}"
                )
            else:
                einsum = (
                    "wtzyx, ijk, lmn, AB, GH, ID,"
                    f" {p1_label}, {p2_label}"
                    f" -> wtzyx{output_label}"
                )

            # ── Sign: -(-1)^(permutation parity) ──
            sign = -1 if _parity(pi) == 0 else 1

            # ── Propagator variable names ──
            # Two spectators → extract flavors
            spec_slots = [s for s in _SLOTS if s != cur_src]
            spec_flavors = sorted(set(src_flav[s] for s in spec_slots))
            # Also find the remaining current flavor sources
            cur_src_slots = [s for s in _SLOTS if src_flav[s] == cur_in]

            # var_a, var_b = the 2 spectator propagator variables
            if len(spec_flavors) == 2:
                fa, fb = spec_flavors
            elif len(spec_flavors) == 1:
                fa = fb = spec_flavors[0]
            else:
                fa = spec_flavors[0] if spec_flavors else cur_in
                fb = spec_flavors[-1] if spec_flavors else cur_out

            # Build description
            desc_parts = []
            for s in _SLOTS:
                t = pi[s]
                thru = conn[s][1]
                if thru:
                    desc_parts.append(
                        f"{src_flav[s]}(src.{s})->[J]->{snk_flav[t]}(snk.{t})"
                    )
                else:
                    desc_parts.append(
                        f"{src_flav[s]}(src.{s})->{snk_flav[t]}(snk.{t})"
                    )
            desc = ", ".join(desc_parts)

            terms.append({
                "einsum": einsum,
                "sign": sign,
                "var_a": _var(fa),
                "var_b": _var(fb),
                "flavor_a": fa,
                "flavor_b": fb,
                "description": desc,
                "n_props": 2,
            })

    return {
        "sink_terms": terms,
        "fwd_var": _var(cur_in),
        "fwd_flavor": cur_in,
        "current_gamma": cur_gamma,
        "n_topologies": len(terms),
    }
