"""Load fake bare-matrix data generated by raw_scripts/generate_fake_data.py."""
# %%
from pathlib import Path

import gvar as gv
import numpy as np

a = 0.0836  # fm
bin = 1
N_bs_samp = 64

FAKE_BARE_DIR = Path(__file__).resolve().parent / "data" / "fake_bare_txt"


def get_fake_qtmdpdf_samp(pz: int, b: int, z: int) -> tuple[np.ndarray, np.ndarray]:
    """Return fake qTMDPDF bootstrap samples for one (pz, b, z) point."""
    arr = np.loadtxt(FAKE_BARE_DIR / "qtmdpdf" / f"pz{pz}_b{b}_z{z}.txt", delimiter=" ")
    return arr[:, 0], arr[:, 1]


def get_fake_qtmdwf_samp(pz: int, b: int, z: int) -> tuple[np.ndarray, np.ndarray]:
    """Return fake qTMDWF bootstrap samples for one (pz, b, z) point."""
    arr = np.loadtxt(FAKE_BARE_DIR / "qtmdwf" / f"pz{pz}_b{b}_z{z}.txt", delimiter=" ")
    return arr[:, 0], arr[:, 1]

if __name__ == "__main__":
    from utils import *
 
    pz = 0
    b = 0
    z_range = np.arange(16)
    
    qtmdwf_fake_re_samp, qtmdwf_fake_im_samp = [], []
    qtmdpdf_fake_re_samp, qtmdpdf_fake_im_samp = [], []

    for z in z_range:
        wf_re, wf_im = get_fake_qtmdwf_samp(pz=pz, b=b, z=int(z))
        pdf_re, pdf_im = get_fake_qtmdpdf_samp(pz=pz, b=b, z=int(z))
        qtmdwf_fake_re_samp.append(wf_re)
        qtmdwf_fake_im_samp.append(wf_im)
        qtmdpdf_fake_re_samp.append(pdf_re)
        qtmdpdf_fake_im_samp.append(pdf_im)
        
    qtmdwf_fake_re_gv = bs_ls_avg(np.asarray(qtmdwf_fake_re_samp), axis=1)
    qtmdwf_fake_im_gv = bs_ls_avg(np.asarray(qtmdwf_fake_im_samp), axis=1)
    qtmdpdf_fake_re_gv = bs_ls_avg(np.asarray(qtmdpdf_fake_re_samp), axis=1)
    qtmdpdf_fake_im_gv = bs_ls_avg(np.asarray(qtmdpdf_fake_im_samp), axis=1)
    
    fig, ax = default_plot()
    ax.errorbar(z_range, gv.mean(qtmdwf_fake_re_gv), gv.sdev(qtmdwf_fake_re_gv), label="Fake qTMDWF Re", **ERRORBAR_STYLE)
    ax.errorbar(z_range, gv.mean(qtmdwf_fake_im_gv), gv.sdev(qtmdwf_fake_im_gv), label="Fake qTMDWF Im", **ERRORBAR_STYLE)

    ax.set_xlabel("z")
    ax.set_ylabel("Value")
    ax.set_title("Fake qTMDWF and qTMDPDF z-dependence")
    ax.legend()
    plt.show()
    
    fig, ax = default_plot()
    ax.errorbar(z_range, gv.mean(qtmdpdf_fake_re_gv), gv.sdev(qtmdpdf_fake_re_gv), label="Fake qTMDPDF Re", **ERRORBAR_STYLE)
    ax.errorbar(z_range, gv.mean(qtmdpdf_fake_im_gv), gv.sdev(qtmdpdf_fake_im_gv), label="Fake qTMDPDF Im", **ERRORBAR_STYLE)
    ax.set_xlabel("z")
    ax.set_ylabel("Value")
    ax.set_title("Fake qTMDWF and qTMDPDF z-dependence")
    ax.legend()
    plt.show()


# %%
